<?php
require ('includes/fpdf/fpdf.php');
	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
class PDF extends FPDF
{
protected $B = 0;
protected $I = 0;
protected $U = 0;
protected $HREF = '';

// Page header
function Header()
{

	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
	// Logo
	$this->Image('logo.png',8,6,200);
	
	$this->Ln(25);
	// Arial 12
$this->SetFont('Arial','B',14);
// Background color
$this->SetTextColor(255);
$this->SetFillColor(0,0,0);
// Title
$this->Cell(195,6,$gh." Hostel Final Merit List (".$session.")",0,1,'C',true);
// Line break
$this->SetTextColor(0);
$this->Ln(1);
$this->SetFont('Times','B',12);
//$this->Cell(200,7,"*Note : Those Who have 'Unverified Remark' Please Visit at 102",0,1,'C');
//$this->Ln();
$this->SetFont('Times','B',10);
$this->Cell(10,7,"MN",1);
        $this->Cell(80,7,"Name of Student",1);
		$this->Cell(35,7,"Class",1);
		$this->Cell(16,7,"Category",1);
		//$this->Cell(25,7,"Category",1);
		$this->Cell(25,7,"MH Merit No.",1);
		//$this->Cell(10,7,"Back",1);
		//$this->Cell(18,7,"Prv.CGPA",1);
		$this->Cell(10,7,"PH",1);
		$this->Cell(18,7,"Remarks",1);
    $this->Ln();
	// Arial bold 15
	/*$this->SetFont('Arial','B',15);
	// Move to the right
	$this->Cell(30);
	// Title
	$this->Cell(150,10,'Government College of Engineering, Jalgaon',1,0,'C');*/
	// Line break
	
}
// Page footer
function Footer()
{
	$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];
	// Position at 1.5 cm from bottom
	$this->SetY(-18);
	$this->SetFont('Arial','B',11);
	//$this->SetFont('Arial','B',10);
	/*$this->Cell(70,5,"Hostel Warden 1",0,0,'C');
	$this->Cell(70,5,"Hostel Warden 2",0,0,'C');*/
	$this->Cell(100,5,"Hostel Rector",0,0,'C');
	$this->Cell(100,5,"Principal",0,0,'C');
	$this->Ln();
	// Arial italic 8
	$this->SetFont('Arial','B',8);
	// Arial italic 8
	//$this->Ln(3);
	$this->Cell(120,4,'CAPS/v4.4/'.$p_ayear.'/'.$p_ses_cat.'/'.$p_gender.'/'.$p_report_format.'/'.date('j-m-Y'),0,1,'L');
	$this->SetFont('Arial','BI',9);
	$this->Cell(127,5,'Auto Generated By CAPS v4.4 Developed By Prof. Harish Gadade & Rizwan R Syed','BT',0,'L');
	$this->Cell(0,3,'Page '.$this->PageNo().'/{nb}',0,0,'R');
	
}


// Load data
function LoadData($file)
{
    // Read file lines
    $lines = file($file);
    $data = array();
    foreach($lines as $line)
        $data[] = explode(';',trim($line));
    return $data;
}

// Simple table
function BasicTable($header, $data)
{
	include 'includes/db_connect.php';
	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	//alert($session);
    $this->SetFont('','B');
	// Header
    $this->SetFont('');
	//$cnt=1;
	$query1=mysqli_query($mysqli,"select * from department where hasres=1")or die(mysqli_error($mysqli));
	while($row1=mysqli_fetch_array($query1))
	{
		$d=$row1['name'];
		$cat_s=$_POST['ses_cat'];
		$query2=mysqli_query($mysqli,"select * from cls WHERE stud_cat='$cat_s' and session='$session'")or die(mysqli_error($mysqli));
		while($row2=mysqli_fetch_array($query2))
		{
			//CLASS
			$myr=$row2['name'];
			$cls=$row2['name']." ".$d;
			//alert($cls);
			//SET FLAG 0
			$cnt=1;
			mysqli_query($mysqli,"UPDATE form_data SET accd=0")or die(mysqli_error($mysqli));
			$query3=mysqli_query($mysqli,"select * from category")or die(mysqli_error($mysqli));
			while($row3=mysqli_fetch_array($query3))
			{
				$cat=$row3['cat'];
				
				$query4=mysqli_query($mysqli,"select * from reserve where category='$cat' and pclass='$cls' and pgender='$gender' and session='$session' and seat_cat='$cat_s'")or die(mysqli_error($mysqli));
				$row4=mysqli_fetch_array($query4);
				$lmt=$row4['seats'];
				//alert($cat." ".$gender." ".$session." ".$lmt." ".$cls);
			$p=0;
			$tcnt=0;
			$vs="s".$row2['lsem']."_back";
			$vss="s".$row2['lsem']."_back ASC";
			if($row2['lsem']==1)
			{
				$psems="s1_sgpa";
				$psem="s1_sgpa DESC";
			}
			else
			{
				$psems="s".($row2['lsem']-1)."_sgpa";
				$psem="s".($row2['lsem']-1)."_sgpa DESC";
			}
					//$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 AND pclass='$cls'  AND pgender='$gender' AND session='$session' ORDER BY $vss,sgpa DESC,$psem")or die(mysqli_error($mysqli));
$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE  accd<>1 AND pclass='$cls'  AND pgender='$gender' AND session='$session' ORDER BY ABS(sgpa) ASC")or die(mysqli_error($mysqli));
				while($row5=mysqli_fetch_array($query5))
				{	
					$id=$row5['sysid'];
					mysqli_query($mysqli,"UPDATE form_data SET accd=1 where sysid='$id'")or die(mysqli_error($mysqli));
					$i=1;
					//if($event==$row5['event']&&$perc==$row5['sgpa'])
					//	alert($cnt);
					if($row5['ver']==1)
						$vers="Verified";
					else
						$vers="Rejected";
					$this->Cell(10,6,$cnt,1);
					$this->Cell(80,6,$row5['pname'],1);
					$this->Cell(35,6,$row5['pclass'],1);
					$this->Cell(16,6,$row5['category'],1);
					$this->Cell(25,6,$row5['sgpa'],1);
					//$this->Cell(10,6,$row5[$vs],1);
//$this->Cell(10,6,$row5[$vs],1);
					//$this->Cell(18,6,$row5[$psems],1);
					$this->Cell(10,6,$row5['ph'],1);
					$this->Cell(18,6,$vers,1);
					$this->Ln();
					$cnt=$cnt+1;
					$tcnt++;
					$event=$row5['event'];
					$perc=$row5['sgpa'];
				}
			
			}
		}
	}
	
}


}


// Instanciation of inherited class
$pdf = new PDF();
$header = array('Name', 'Branch & Year', 'Category', 'Remarks');
// Data loading

$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('times','',10);


$pdf->BasicTable($header,$data);
//	$pdf->Output();
$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];
	$pdf->Output($p_report_format." - Final Merit List - ".$p_ayear." - ".$p_ses_cat." - ".$p_gender.".pdf", 'D');
	
	?>
