<?php
require ('includes/fpdf/fpdf.php');
	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	$ses_cat=$_POST['ses_cat'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
	//alert($session);
	//alert($gender);
	
	
	//alert($gender);
class PDF extends FPDF
{
protected $B = 0;
protected $I = 0;
protected $U = 0;
protected $HREF = '';

// Page header
function Header()
{

	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	$ses_cat=$_POST['ses_cat'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
	//alert($session);
	//alert($gender);
	
	// Logo
	$this->Image('logo.png',40,6,200);
	
	$this->Ln(25);
	// Arial 12
$this->SetFont('Arial','B',14);
// Background color
$this->SetTextColor(255);
$this->SetFillColor(0,0,0);
// Title
$this->Cell(280,6,$gh." Hostel Waiting List (".$session.")",0,1,'C',true);
// Line break
$this->SetTextColor(0);
$this->Ln(1);
$this->SetFont('Times','B',12);
//$this->Cell(200,7,"*Note : Those Who have 'Unverified Remark' Please Visit at 102",0,1,'C');
//$this->Ln();
$this->SetFont('courier','B',12);
$this->Cell(9,6,"MN",1);
        $this->Cell(80,6,"Name of Student",1);
		$this->Cell(44,6,"Class",1);
		$this->Cell(23,6,"Category",1);
		//$this->Cell(25,7,"Category",1);
		$this->Cell(40,6,"MH Merit No.",1);
		//$this->Cell(15,6,"Back",1);
		//$this->Cell(20,6,"Prev. %",1);
		$this->Cell(12,6,"PH",1);
		$this->Cell(72,6,"Seat Status",1);
    $this->Ln();
	// Arial bold 15
	/*$this->SetFont('Arial','B',15);
	// Move to the right
	$this->Cell(30);
	// Title
	$this->Cell(150,10,'Government College of Engineering, Jalgaon',1,0,'C');*/
	// Line break
	
}
// Page footer
function Footer()
{
	$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];
	// Position at 1.5 cm from bottom
	$this->SetY(-20);
	$this->Ln();
	$this->SetFont('Arial','B',10);
	//$this->SetFont('Arial','B',10);
	$this->Cell(70,5,"Hostel Warden 1",0,0,'C');
	$this->Cell(70,5,"Hostel Warden 2",0,0,'C');
	$this->Cell(70,5,"Hostel Rector",0,0,'C');
	$this->Cell(70,5,"Principal",0,0,'C');
	$this->Ln();
	// Arial italic 8
	$this->SetFont('Arial','B',8);
	// Arial italic 8
	//$this->Ln(3);
	$this->Cell(120,4,'CAPS/v4.4/'.$p_ayear.'/'.$p_ses_cat.'/'.$p_gender.'/'.$p_report_format.'/'.date('j-m-Y'),0,1,'L');
	$this->SetFont('Arial','BI',9);
	$this->Cell(127,4,'Auto Generated By CAPS v4.4 Developed By Prof. Harish Gadade & Rizwan R Syed','BT',0,'L');
	$this->Cell(0,3,'Page '.$this->PageNo().'/{nb}',0,0,'R');
	}


// Load data
function LoadData($file)
{
    // Read file lines
    $lines = file($file);
    $data = array();
    foreach($lines as $line)
        $data[] = explode(';',trim($line));
    return $data;
}

// Simple table
function BasicTable($header, $data)
{

	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	$ses_cat=$_POST['ses_cat'];
	//alert($ses_cat);

	include('includes/db_connect.php');

    $this->SetFont('courier','B',10);
	// Header
    //foreach($header as $col)
		/*$this->Cell(10,7,"SN",1);
        $this->Cell(75,7,"Name of Student",1);
		$this->Cell(52,7,"Class",1);
		$this->Cell(25,7,"Category",1);
		//$this->Cell(25,7,"Category",1);
		$this->Cell(20,7,"Percent",1);
		$this->Cell(12,7,"Back",1);
    $this->Ln();*/
    $this->SetFont('');
	$cnt=1;
$cat_s=$_POST['ses_cat'];
	mysqli_query($mysqli,"UPDATE form_data SET stype='',sagn='' WHERE form_cat='$cat_s'")or die(mysqli_error($mysqli));
	$query1=mysqli_query($mysqli,"select * from department where hasres=1")or die(mysqli_error($mysqli));
	while($row1=mysqli_fetch_array($query1))
	{
		$d=$row1['name'];
		
		$query2=mysqli_query($mysqli,"select * from cls  WHERE stud_cat='$cat_s' and session='$session'")or die(mysqli_error($mysqli));
		while($row2=mysqli_fetch_array($query2))
		{
			//CLASS
			$myr=$row2['name'];
			$cls=$row2['name']." ".$d;
			
			
			//SET FLAG 0
			//mysqli_query("UPDATE form_data SET stype='' WHERE form_cat='$cat_s'")or die(mysqli_error());
			mysqli_query($mysqli,"UPDATE form_data SET accd=0 WHERE form_cat='$cat_s'")or die(mysqli_error($mysqli));
			$query3=mysqli_query($mysqli,"select * from category ORDER BY rprt ")or die(mysqli_error($mysqli));
			while($row3=mysqli_fetch_array($query3))
			{
				$cat=$row3['cat'];
				
				$query4=mysqli_query($mysqli,"select * from reserve where category='$cat' and pclass='$cls' and pgender='$gender' and session='$session' and seat_cat='$cat_s'")or die(mysqli_error($mysqli));
				$row4=mysqli_fetch_array($query4);
				$lmt=$row4['seats'];
				//alert($cat." ".$gender." ".$session." ".$lmt." ".$cls);
			$p=0;
			$tcnt=0;
			$vs="s".$row2['lsem']."_back";
			$vss="s".$row2['lsem']."_back ASC";
			if($row2['lsem']==1)
			{
				$psems="s1_sgpa";
				$psem="s1_sgpa DESC";
			}
			else
			{
				$psems="s".($row2['lsem']-1)."_sgpa";
				$psem="s".($row2['lsem']-1)."_sgpa DESC";
			}
				if($cat=="Open")
				{
					$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
				}
				else if($cat=="PH")
				{
					$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 and ph='yes' AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
				}
				else
				{
					//$query4=mysqli_query("select * from reserve where category='$cat' and pclass='$cls' and pgender='$gender' and session='$session'")or die(mysqli_error());
					//$row2=mysqli_fetch_array($query2);
					//$lmt=$row2['seats'];
					$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 and category='$cat' AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
				}
				
				
				while($row5=mysqli_fetch_array($query5))
				{	
					$id=$row5['sysid'];
					mysqli_query($mysqli,"UPDATE form_data SET accd=1, stype='$cat', sagn='$cat'where sysid='$id'")or die(mysqli_error($mysqli));
					$i=1;
					//if($category==$row5['category']&&$perc==$row5['sgpa'])
					//	alert($cnt);
					if($row5['ver']==1)
						$vers="Verified";
					else
						$vers="Unverified";
					$cnt=$cnt+1;
					$tcnt++;
					$category=$row5['category'];
					$perc=$row5['sgpa'];
				}
				
				//***************************************Remain*************************************************************
				
				$nrw=mysqli_num_rows($query5);
				
				//alert($cls." ".$cat." ".$nrw." ".$lmt);
				/*while($nrw<$lmt)
				{
					//alert($cls." ".$cat." ".$nrw." ".$lmt);
					$lmt=$lmt-$nrw;
					//alert($cls." ".$cat." ".$nrw." ".$lmt);
					$query33=mysqli_query($mysqli,"select * from category WHERE cat<>'PH' ORDER BY prt ASC")or die(mysqli_error($mysqli));
					while(($row33=mysqli_fetch_array($query33))&&$lmt)
					{
						
						$cat1=$row33['cat'];
						
						$query55=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 and category='$cat1' AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
						while($row55=mysqli_fetch_array($query55))
						{
							//alert($cls." ".$cat." ".$cat1." ".$lmt);
							$id=$row55['sysid'];
							mysqli_query($mysqli,"UPDATE form_data SET accd=1, stype='$cat', sagn='$cat1' where sysid='$id'")or die(mysqli_error($mysqli));
							$i=1;
					
							$cnt=$cnt+1;
							$tcnt++;
							$category=$row55['category'];
							$perc=$row55['sgpa'];
						}
						$lmt=$lmt-mysqli_num_rows($query55);
					}
					
					
				}*/
			}
		}
	}
	
	/***************************Remain New **************************************************/



	$query1=mysqli_query($mysqli,"select * from department where hasres=1")or die(mysqli_error($mysqli));
	while($row1=mysqli_fetch_array($query1))
	{
		$d=$row1['name'];
		$cat_s=$_POST['ses_cat'];
		$query2=mysqli_query($mysqli,"select * from cls  WHERE stud_cat='$cat_s' and session='$session'")or die(mysqli_error($mysqli));
		while($row2=mysqli_fetch_array($query2))
		{
			//CLASS
			$myr=$row2['name'];
			$cls=$row2['name']." ".$d;
			
			
			//SET FLAG 0
			//mysqli_query("UPDATE form_data SET stype='' ")or die(mysqli_error());
			//mysqli_query($mysqli,"UPDATE form_data SET accd=0")or die(mysqli_error($mysqli));
			$query3=mysqli_query($mysqli,"select * from category WHERE cat<>'PH' AND cat<>'Open' ORDER BY rprt ")or die(mysqli_error($mysqli));
			while($row3=mysqli_fetch_array($query3))
			{
				$cat=$row3['cat'];
				
				$query4=mysqli_query($mysqli,"select * from reserve where category='$cat' and pclass='$cls' and pgender='$gender' and session='$session' and seat_cat='$cat_s'")or die(mysqli_error($mysqli));
				$row4=mysqli_fetch_array($query4);
				$lmt=$row4['seats'];
				$vs="s".$row2['lsem']."_back";
			$vss="s".$row2['lsem']."_back ASC";
			if($row2['lsem']==1)
			{
				$psems="s1_sgpa";
				$psem="s1_sgpa DESC";
			}
			else
			{
				$psems="s".($row2['lsem']-1)."_sgpa";
				$psem="s".($row2['lsem']-1)."_sgpa DESC";
			}
				//alert($cat." ".$gender." ".$session." ".$lmt." ".$cls);
					$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 and sagn='$cat' AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
				
				
				
				//***************************************Remain*************************************************************
				
				$nrw=mysqli_num_rows($query5);
				
				//alert($cls." ".$cat." A-".$nrw." R-".$lmt);
				while($nrw<$lmt&&($cls!="SY Instrumentation"))
				{
					//alert("1- ".$cls." ".$cat." ".$nrw." ".$lmt);
					$lmt=$lmt-$nrw;
					//alert("2- ".$cls." ".$cat." ".$nrw." ".$lmt);
					$query33=mysqli_query($mysqli,"select * from category WHERE cat<>'PH'  ORDER BY prt ASC")or die(mysqli_error($mysqli));
					$cstc=1;
					$fz=0;
					while(($row33=mysqli_fetch_array($query33))&&$lmt)
					{
						
						$cat1=$row33['cat'];
						
						$query55=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 AND sagn='' and category='$cat1' AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND  form_cat='$cat_s' ORDER BY ABS(sgpa) ASC LIMIT $lmt")or die(mysqli_error($mysqli));
						while($row55=mysqli_fetch_array($query55))
						{
							//alert("3- ".$cls." ".$cat." ".$cat1." ".$lmt);
							$id=$row55['sysid'];
							mysqli_query($mysqli,"UPDATE form_data SET accd=1, stype='$cat', sagn='$cat1' where sysid='$id'")or die(mysqli_error($mysqli));
							$i=1;
					
							
						}
						$cstc++;
						//alert(mysqli_num_rows($query55)." ".$cat1." ".$cstc);
						
						$lmt=$lmt-mysqli_num_rows($query55);
					}
					$lmt=0;
					
					
				}
			}
		}
	}
	/***********************************Cancellation**************************************/
	mysqli_query($mysqli,"UPDATE form_data SET stype='Waiting' WHERE stype='' AND ver=1 AND form_cat='$cat_s'")or die(mysqli_error($mysqli));
	mysqli_query($mysqli,"UPDATE form_data SET pcan=0 WHERE ver=1 AND form_cat='$cat_s'")or die(mysqli_error($mysqli));
	$query12=mysqli_query($mysqli,"select * from form_data where canc=1 AND ver=1 AND form_cat='$cat_s' ORDER BY ABS(sgpa), pclass,pgender")or die(mysqli_error($mysqli));
	while($row12=mysqli_fetch_array($query12))
	{
		$ido=$row12['sysid'];
		$mycat=$row12['stype'];
		$mycls=$row12['pclass'];
		$mygen=$row12['pgender'];
		$session=$row12['session'];
		$arr = explode(' ',trim($mycls));
		$ccls=$arr[0];
		$query2=mysqli_query($mysqli,"select * from cls WHERE name='$ccls'")or die(mysqli_error($mysqli));
		$row2=mysqli_fetch_array($query2);
		if($mycat=="PH")
		{
			$mycat="Open";
			$mycat1="PH";
		}
			$vs="s".$row2['lsem']."_back";
			$vss="s".$row2['lsem']."_back ASC";
			if($row2['lsem']==1)
			{
				$psems="s1_sgpa";
				$psem="s1_sgpa DESC";
			}
			else
			{
				$psems="s".($row2['lsem']-1)."_sgpa";
				$psem="s".($row2['lsem']-1)."_sgpa DESC";
			}
		mysqli_free_result($query2);	
//alert($mycls." - ".$ccls);
					$isd=1;
					if($mycat=="Open")
					{
						//alert($row12['pname']);	
					$query55=mysqli_query($mysqli,"SELECT * FROM form_data 

WHERE ver=1 AND accd<>1 AND stype='Waiting'  AND pclass='$mycls'  AND pgender='$mygen' 

AND session='$session' AND canc<>1 AND form_cat='$cat_s' ORDER BY ABS(sgpa) LIMIT 1")or die(mysqli_error($mysqli));
						while($row55=mysqli_fetch_array($query55))
						{
							$id=$row55['sysid'];
						if($mycat1=="PH")
							$mycat="Open-PH";	
							mysqli_query($mysqli,"UPDATE form_data 

SET stype='$mycat', sagn='$mycat', pcan=1 where sysid='$id'")or die(mysqli_error($mysqli));
							mysqli_query($mysqli,"UPDATE form_data 

SET stype='Not Alloted', sagn='Not Alloted', pcan=1 where sysid='$ido'")or die(mysqli_error($mysqli));
							$isd=0;
							$category=$row55['category'];
							//alert($row55['pname']);
						}
					}
					else
					{

					mysqli_query($mysqli,"UPDATE category SET tprt=1 WHERE 

cat='$mycat'");
					$query33=mysqli_query($mysqli,"select * from category WHERE 

cat<>'PH' ORDER BY tprt ASC")or die(mysqli_error($mysqli));
					//alert($row12['pname']);
					while(($row33=mysqli_fetch_array($query33))&&$isd)
					{
						
						$cat1=$row33['cat'];
						$query55=mysqli_query($mysqli,"SELECT * FROM 

form_data WHERE ver=1 AND accd<>1 AND stype='Waiting' and category='$cat1' AND 

pclass='$mycls'  AND pgender='$mygen' AND session='$session' AND canc<>1 AND form_cat='$cat_s' ORDER BY ABS(sgpa) 

 LIMIT 1")or die(mysqli_error($mysqli));
						while($row55=mysqli_fetch_array($query55))
						{
							$id=$row55['sysid'];
						if($mycat1=="PH")
							$mycat="Open-PH";	
							mysqli_query($mysqli,"UPDATE form_data 

SET stype='$mycat', sagn='$mycat', pcan=1 where sysid='$id'")or die(mysqli_error($mysqli));
							mysqli_query($mysqli,"UPDATE form_data 

SET stype='Not Alloted', sagn='Not Alloted', pcan=1 where sysid='$ido'")or die(mysqli_error($mysqli));
					//alert($row12['pname']." - ".$row55['pname']." - ".$mycat);
							$isd=0;
							$category=$row55['category'];
							$perc=$row55['sgpa'];
						}
					}
					}
			mysqli_query($mysqli,"UPDATE category SET tprt=tprto");
		
	}
	
	
	/***********************************Cancellation**************************************/
	
	
	
	
	/***********************************List Generation***********************************/
	//mysqli_query("UPDATE form_data SET stype='Waiting' WHERE stype=''")or die(mysqli_error());
					
	$query1=mysqli_query($mysqli,"select * from department where hasres=1")or die(mysqli_error($mysqli));
	while($row1=mysqli_fetch_array($query1))
	{
		$d=$row1['name'];
		$query2=mysqli_query($mysqli,"select * from cls  WHERE stud_cat='$ses_cat' and session='$session'")or die(mysqli_error($mysqli));
		while($row2=mysqli_fetch_array($query2))
		{
			//CLASS
			$myr=$row2['name'];
			$cls=$row2['name']." ".$d;
			//alert($cls);
			//SET FLAG 0
			$cnt=1;
			mysqli_query($mysqli,"UPDATE form_data SET accd=0")or die(mysqli_error($mysqli));
			$query3=mysqli_query($mysqli,"select * from category")or die(mysqli_error($mysqli));
			while($row3=mysqli_fetch_array($query3))
			{
				$cat=$row3['cat'];
				
				$query4=mysqli_query($mysqli,"select * from reserve where category='$cat' and pclass='$cls' and pgender='$gender' and session='$session' AND seat_cat='$cat_s'")or die(mysqli_error($mysqli));
				$row4=mysqli_fetch_array($query4);
				$lmt=$row4['seats'];
				//alert($cat." ".$gender." ".$session." ".$lmt." ".$cls);
			$p=0;
			$tcnt=0;
			$vs="s".$row2['lsem']."_back";
			$vss="s".$row2['lsem']."_back ASC";
			if($row2['lsem']==1)
			{
				$psems="s1_sgpa";
				$psem="s1_sgpa DESC";
			}
			else
			{
				$psems="s".($row2['lsem']-1)."_sgpa";
				$psem="s".($row2['lsem']-1)."_sgpa DESC";
			}
			//alert($vss);
					$query5=mysqli_query($mysqli,"SELECT * FROM form_data WHERE ver=1 AND accd<>1 AND pclass='$cls'  AND pgender='$gender' AND session='$session' AND form_cat='$cat_s' ORDER BY ABS(sgpa)")or die(mysqli_error($mysqli));
				
				while($row5=mysqli_fetch_array($query5))
				{	
					if($row5['pcan']==1||$row5['stype']=="Waiting")
					{
					$id=$row5['sysid'];
					mysqli_query($mysqli,"UPDATE form_data SET accd=1 where sysid='$id'")or die(mysqli_error($mysqli));
					$i=1;
					//if($category==$row5['category']&&$perc==$row5['sgpa'])
					//	alert($cnt);
					if($row5['ver']==1)
						$vers="Verified";
					else
						$vers="Unverified";
					$this->Cell(9,5,$cnt,1);
					$this->Cell(80,5,$row5['pname'],1);
					$this->Cell(44,5,$row5['pclass'],1);
					$this->Cell(23,5,$row5['category'],1);
					$this->Cell(40,5,$row5['sgpa'],1);
					//$pdf->Cell(15,5,$row5[$vs],1);
					//$pdf->Cell(20,5,$row5[$psems],1);
					$this->Cell(12,5,$row5['ph'],1);
					if($row5['stype']=="Not Alloted")
						$this->Cell(72,5,"Not Alloted/Cancelled",1);
					else if ($row5['stype']=="Waiting")
						$this->Cell(72,5,"Waiting",1);
					else
						$this->Cell(72,5,"Selected Against - ".$row5['stype'],1);
					$this->Ln();
					$cnt=$cnt+1;
					$tcnt++;
					$category=$row5['category'];
					$perc=$row5['sgpa'];
					}
					else
						$cnt=$cnt+1;
				}
			}
		}
	}
}



}


// Instanciation of inherited class
$pdf = new PDF('L','mm','A4');
$header = array('Name', 'Branch & Year', 'Category', 'Remarks');
$pdf->AliasNbPages();
$pdf->AddPage('L');
$pdf->SetFont('times','',8);
$pdf->BasicTable($header,$data);
//$pdf->Output();
$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];
	$pdf->Output($p_report_format." - Waiting List - ".$p_ayear." - ".$p_ses_cat." - ".$p_gender.".pdf", 'D');
	
	?>
