<?php
require ('../Admin/includes/fpdf/fpdf.php');
	
	$m_pemail=$_POST['email'];
	$m_pses=$_POST['ayear'];
	$m_ses=$_POST['ses_cat'];
	$query=mysqli_query($mysqli,"SELECT * FROM form_data WHERE pemail='$m_pemail' and session='$m_pses' and form_cat='$m_ses'");
	if(mysqli_num_rows($query))
	{
		$query=mysqli_query($mysqli,"SELECT * FROM form_data WHERE pemail='$m_pemail' and session='$m_pses' and form_cat='$m_ses'");
		$row=mysqli_fetch_array($query);
		$m_pname=$row['pname'];
		$m_pc_no=$row['pc_no'];
		$m_psc_no=$row['psc_no'];
		$m_pgender=$row['pgender'];
		$m_pclgname=$row['sgpa'];
		$m_pbranch=$row['pclass'];
		$m_event=$row['category'];
		$m_membs=$row['membs'];
		$m_accd=$row['accd'];
		$m_padd=$row['padd'];
		$m_ladd=$row['ladd'];
		$m_ph=$row['ph'];
		$m_def=$row['def'];
		$m_jk=$row['jk'];
		$cuid=$row['uid'];
		$pdate=$row['date'];
		$ses=$row['session'];
$m_ai_mn=$row['ai_mn'];
		$m_prn=$row['prn'];
		$version=$row['f_version'];
		if($m_pgender=="Male")
			$gh="Boy's";
		else if($m_pgender=="Female")
			$gh="Girl's";
		$i=1;
		while($i<6)
		{
			$res="s".$i."_result";
			$back="s".$i."_back";
			$sgpa="s".$i."_sgpa";
			${"result".$i}=$row[$res];
			${"back".$i}=$row[$back];
			${"sgpa".$i}=$row[$sgpa];
			$i=$i+1;
		}
	}
	else
	{
		?>
		<script type="text/javascript">
			alert("Please fill the form first");
			document.location="index.php";
		</script>
		<?php
	}
//}
class PDF extends FPDF
{
protected $B = 0;
protected $I = 0;
protected $U = 0;
protected $HREF = '';

// Page header
function Header()
{
	// Logo
	$this->Image('logo.png',8,6,195);
	// Line break
	$this->Ln(25);
}
// Page footer
function Footer()
{
	$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_report_format="S01";
	// Position at 1.5 cm from bottom
	$this->SetY(-15);
	// Arial italic 8
	$this->SetFont('Arial','B',8);
	// Arial italic 8
	//$this->Ln(3);
	$this->Cell(120,4,'CAPS/v4.4/'.$p_ayear.'/'.$p_ses_cat.'/'.$p_report_format.'/'.date('j-m-Y'),0,1,'L');
	$this->SetFont('Arial','BI',9);
	$this->Cell(127,5,'Auto Generated By CAPS v4.4 Developed By Prof. Harish Gadade & Rizwan R Syed','BT',0,'L');
	$this->Cell(0,3,'Page '.$this->PageNo().'/{nb}',0,0,'R');
}

function WriteHTML($html)
{
    // HTML parser
	$html = str_replace("\n",' ',$html);
    $a = preg_split('/<(.*)>/U',$html,-1,PREG_SPLIT_DELIM_CAPTURE);
    foreach($a as $i=>$e)
    {
        if($i%2==0)
        {
            // Text
            if($this->HREF)
                $this->PutLink($this->HREF,$e);
            else
                $this->Write(5,$e);
        }
        else
        {
            // Tag
            if($e[0]=='/')
                $this->CloseTag(strtoupper(substr($e,1)));
            else
            {
                // Extract attributes
                $a2 = explode(' ',$e);
                $tag = strtoupper(array_shift($a2));
                $attr = array();
                foreach($a2 as $v)
                {
                    if(preg_match('/([^=]*)=["\']?([^"\']*)/',$v,$a3))
                        $attr[strtoupper($a3[1])] = $a3[2];
                }
                $this->OpenTag($tag,$attr);
            }
        }
    }
}


function BasicTable($header, $data)
{
	
		$m_pemail=$_POST['email'];
		$query=mysql_query("SELECT * FROM form_data WHERE pemail='$m_pemail'");
		$row=mysql_fetch_array($query);
		$m_pname=$row['pname'];
		$cuid=$row['uid'];
	
    $this->SetFont('','B');
	// Header
    //foreach($header as $col)
	$this->Cell(10,7,"SN",1,0,'C');
    $this->Cell(25,7,"Semester",1,0,'C');
	$this->Cell(50,7,"Pass / ATKT / Fail",1,0,'C');
	$this->Cell(75,7,"If Fail / ATKT, No. of Subjects Failed",1,0,'C');
	$this->Cell(50,7,"CGPA",1,0,'C');
		//$this->Cell(25,7,"Category",1);
		//$this->Cell(25,7,"Remarks",1);
    $this->Ln();
    $this->SetFont('');
	$i=1;
	while($i<6)
	{
		
		if(!(${"result".$i}=="Not A"||${"result".$i}=="Select"||${"result".$i}=="Not Applicable"||${"result".$i}=="Not A "||${"result".$i}==""||strcmp(${"result".$i},"Not A")==0))
		{
			$this->Cell(10,7,$i,1,0,'C');
			$this->Cell(25,7,$i,1,0,'C');
			$this->Cell(50,7,${"result".$i},1,0,'C');
			$this->Cell(75,7,${"back".$i},1,0,'C');
			$this->Cell(50,7,${"sgpa".$i},1,0,'C');
			$this->Ln();
		}
		$i=$i+1;
	}
	
}


function OpenTag($tag, $attr)
{
    // Opening tag
    if($tag=='B' || $tag=='I' || $tag=='U')
        $this->SetStyle($tag,true);
    if($tag=='A')
        $this->HREF = $attr['HREF'];
    if($tag=='BR')
        $this->Ln(5);
}

function CloseTag($tag)
{
    // Closing tag
    if($tag=='B' || $tag=='I' || $tag=='U')
        $this->SetStyle($tag,false);
    if($tag=='A')
        $this->HREF = '';
}

function SetStyle($tag, $enable)
{
    // Modify style and select corresponding font
    $this->$tag += ($enable ? 1 : -1);
    $style = '';
    foreach(array('B', 'I', 'U') as $s)
    {
        if($this->$s>0)
            $style .= $s;
    }
    $this->SetFont('',$style);
}

function PutLink($URL, $txt)
{
    // Put a hyperlink
    $this->SetTextColor(0,0,255);
    $this->SetStyle('U',true);
    $this->Write(5,$txt,$URL);
    $this->SetStyle('U',false);
    $this->SetTextColor(0);
}


}


// Instanciation of inherited class
$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->Image('photo.png',160,45,40,50);
// Arial 12
$pdf->SetFont('Arial','B',14);
$pdf->SetTextColor(255);
// Background color
$pdf->SetFillColor(0,0,0);
// Title
$pdf->Cell(190,7,"Application Form for ".$gh." Hostel Admission - ".$ses." (Version :".$version.")",0,1,'C',true);
// Line break
$pdf->Ln(4);
//$pdf->SetFont('');
$pdf->SetFont('Arial','',12);
$pdf->SetTextColor(0);
$html2='           I have read all the rules of hostel admission and after understanding these rules thoroughly, I have filled in the application form for admission of current year. The information given by me in my application is true to the best of my knowledge and belief. I understand that if any of the statements made by me in the application form or any information/documents supplied by me in connection with my admission is found to be false or incorrect at any stage, my admission will be cancelled. I hereby agree that I will be bound to all Rules, Acts and Laws set by State Government. I hereby undertake that, I will follow all the rules and regulation of the hostel, failing which will be liable for disciplinary action.';
$pdf->Cell(20,7,"Name : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(100,7,$m_pname,'B',1,'L');
$pdf->SetFont('');
$pdf->Cell(20,7,"Email : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(100,7,$m_pemail,'B',1,'L');
$pdf->SetFont('');
//$pdf->Ln();
$pdf->Cell(55,7,"Parents Contact Number : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(30,7,$m_psc_no,'B',1,'C');
$pdf->SetFont('');
$pdf->Cell(55,7,"Candidate Contact Number : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(30,7,$m_pc_no,'B',1,'C');

$pdf->SetFont('');
$pdf->Cell(25,7,"Category : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(15,7,$m_event,'B',0,'C');
$pdf->SetFont('');
$pdf->Cell(10,7,"",0,0,'L');
$pdf->Cell(20,7,"Gender : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(18,7,$m_pgender,'B',1,'C');

$pdf->SetFont('');
$pdf->Cell(50,7,"Physically Handicapped : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(12,7,$m_ph,'B',0,'C');
$pdf->SetFont('');
$pdf->Cell(10,7,"",0,0,'L');
$pdf->Cell(20,7,"Defence : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(12,7,$m_def,'B',1,'C');
$pdf->SetFont('');
//$pdf->Cell(7,7,"",0,0,'L');
$pdf->Cell(65,7,"J & K / North Eastern Candidate : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(12,7,$m_jk,'B',1,'C');
$pdf->SetFont('');
$pdf->Cell(48,7,"Current Year & Branch :",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(72,7,$m_pbranch,'B',0,'C');
$pdf->SetFont('');
$pdf->Cell(12,7,"PRN :",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(20,7,$m_prn,'B',1,'C');
$pdf->SetFont('');
$pdf->Cell(42,8,"Permanent Address :",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(150,8,$m_padd,'B',1,'L');
$pdf->SetFont('');
$pdf->Cell(42,8,"Local Address :",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(150,8,$m_ladd,'B',1,'L');
$pdf->SetFont('');
$pdf->Cell(50,7,"Latest Semester SGPA : ",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(20,7,$m_pclgname,'B',0,'C');
$pdf->Ln();
$pdf->Cell(0,6,"Academic Details (Submission of relevant attested documents are necessary)",0,1,'L');
//$pdf->BasicTable($header,$data);


$pdf->SetFont('','B');
// Header
//foreach($header as $col)
	$pdf->Cell(10,7,"SN",1,0,'C');
	$pdf->Cell(25,7,"Semester",1,0,'C');
	$pdf->Cell(50,7,"Pass / ATKT / Fail",1,0,'C');
	$pdf->Cell(75,7,"If Fail / ATKT, No. of Subjects Failed",1,0,'C');
	$pdf->Cell(25,7,"CGPA",1,0,'C');
	//$pdf->Cell(25,7,"Category",1);
//$pdf->Cell(25,7,"Remarks",1);
$pdf->Ln();
$pdf->SetFont('');
$i=1;
while($i<6)
{
	
	if(!(${"result".$i}=="Not Applicable"||${"result".$i}=="Select"||${"result".$i}==""))
	{
		$pdf->Cell(10,7,$i,1,0,'C');
		$pdf->Cell(25,7,$i,1,0,'C');
		$pdf->Cell(50,7,${"result".$i},1,0,'C');
		$pdf->Cell(75,7,${"back".$i},1,0,'C');
		$pdf->Cell(25,7,${"sgpa".$i},1,0,'C');
		$pdf->Ln();
	}
	$i=$i+1;
}


$pdf->Ln();
$pdf->WriteHTML($html2);
$pdf->Ln(10);
$pdf->Cell(30,6,"Date & Time : ",0,0,'L');
$pdf->Cell(0,6,$pdate,0,1,'L');
$pdf->Cell(0,6,"Place : Jalgaon",0,0,'L');
$pdf->SetFont('','B');
$pdf->Cell(0,6,"Signature of Candidate",0,1,'R');
$pdf->SetFont('');
$pdf->Cell(0,1," ",'B',1);
$pdf->Cell(0,7,"For Office Use : ",0,1,'L');
$pdf->Cell(120,6,"Receipt of Hostel rent charges Rs. 500/-",0,0,'L');
$pdf->Cell(27,6,"Receipt No.",0,0,'L');
$pdf->Cell(40,6,"",'B',1,'L');
$pdf->Cell(0,6,"Room Alloted : Room No.",0,1,'L');
$pdf->Ln(10);
$pdf->SetFont('','B');
$pdf->Cell(100,6,"Hostel Clerk Signature",0,0,'C');
$pdf->Cell(100,6,"Hostel Rector Signature",0,1,'C');
$pdf->SetFont('');
//$pdf->Output();
$pdf->Output("Hostel_Form_".$m_prn.".pdf", 'D');
//header('Content-Type: application/octet-stream');
//header('Content-Length: ' . FILESIZE_HERE);
//header('Content-Disposition: attachment; filename=' . "Hostel_From_".$m_pname.".pdf");

//header("Location : ../");
?>
