<?php
require ('includes/fpdf/fpdf.php');
	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
class PDF extends FPDF
{
protected $B = 0;
protected $I = 0;
protected $U = 0;
protected $HREF = '';

// Page header
function Header()
{
include('includes/db_connect.php');

	$gender=$_POST['gender'];
	$session=$_POST['ayear'];
	if($gender=="Male")
		$gh="Boys";
	else
		$gh="Girls";
	// Logo
	$this->Image('logo.png',8,6,200);
	
	$this->Ln(25);
	// Arial 12
$this->SetFont('Arial','B',14);
// Background color
$this->SetTextColor(255);
$this->SetFillColor(0,0,0);
// Title
$this->Cell(195,6,$gh." Hostel Seat Distribution Chart (".$session.")",0,1,'C',true);
// Line break
$this->SetTextColor(0);
$this->Ln(1);
$this->SetFont('Times','B',12);
//$this->Cell(200,7,"*Note : Those Who have 'Unverified Remark' Please Visit at 102",0,1,'C');
//$this->Ln();
$this->SetFont('Times','B',10);
        
		$this->Cell(30,6,"Category >>>",1);
		
		//$this->Cell(25,7,"Category",1);
		/*$this->Cell(15,7,"Percent",1);
		$this->Cell(10,7,"Back",1);
		$this->Cell(15,7,"Prev. %",1);
		$this->Cell(10,7,"PH",1);
		$this->Cell(18,7,"Remarks",1);*/

	$query20=mysqli_query($mysqli,"SELECT DISTINCT cat FROM category ORDER BY uid") or die(mysqli_error());
	while($row20=mysqli_fetch_array($query20))
	{
		$this->Cell(27,6,$row20['cat'],1,0,'C');
		
	}
	


    $this->Ln();
	$this->Cell(30,6,"Class",1);
	$query20=mysqli_query($mysqli,"SELECT DISTINCT cat FROM category ORDER BY uid") or die(mysqli_error());
	while($row20=mysqli_fetch_array($query20))
	{
		$this->Cell(13,6,"Seats",1,0,'C');
		$this->Cell(14,6,"Forms",1,0,'C');
		
	}
	$this->Ln();
	// Arial bold 15
	/*$this->SetFont('Arial','B',15);
	// Move to the right
	$this->Cell(30);
	// Title
	$this->Cell(150,10,'Government College of Engineering, Jalgaon',1,0,'C');*/
	// Line break
	
}
// Page footer
function Footer()
{
	$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];

	// Position at 1.5 cm from bottom
	$this->SetY(-18);
	$this->SetFont('Arial','B',10);
	//$this->SetFont('Arial','B',10);
	$this->Cell(50,5,"Hostel Warden 1",0,0,'C');
	$this->Cell(50,5,"Hostel Warden 2",0,0,'C');
	$this->Cell(50,5,"Hostel Rector",0,0,'C');
	$this->Cell(50,5,"Principal",0,0,'C');
	$this->Ln();
	// Arial italic 8
	$this->SetFont('Arial','B',8);
	// Arial italic 8
	//$this->Ln(3);
	$this->Cell(120,4,'CAPS/v4.4/'.$p_ayear.'/'.$p_ses_cat.'/'.$p_gender.'/'.$p_report_format.'/'.date('j-m-Y'),0,1,'L');
	$this->SetFont('Arial','BI',9);
	$this->Cell(127,5,'Auto Generated By CAPS v4.4 Developed By Prof. Harish Gadade & Rizwan R Syed','BT',0,'L');
	$this->Cell(0,3,'Page '.$this->PageNo().'/{nb}',0,0,'R');	
}


// Load data
function LoadData($file)
{
    // Read file lines
    $lines = file($file);
    $data = array();
    foreach($lines as $line)
        $data[] = explode(';',trim($line));
    return $data;
}

// Simple table
function BasicTable($header, $data)
{
	include 'includes/db_connect.php';
	$gender=$_POST['gender'];
	$session_year=$_POST['ayear'];
	$cat=$_POST['ses_cat'];
	//alert($session_year);
    $this->SetFont('','B');
	// Header
    $this->SetFont('');
	/*$this->Cell(28,6,$gender,1);
	$this->Cell(28,6,$session_year,1);*/
	$query3=mysqli_query($mysqli,"SELECT DISTINCT name FROM gender WHERE name='$gender' ORDER BY uid") or die(mysqli_error($mysqli));
	while($row3=mysqli_fetch_array($query3))
	{
		$g=$row3['name'];
		$query4=mysqli_query($mysqli,"SELECT DISTINCT name FROM department WHERE hasres=1 ORDER BY uid") or die(mysqli_error($mysqli));
		while($row4=mysqli_fetch_array($query4))
		{
			$d=$row4['name'];
			$query5=mysqli_query($mysqli,"SELECT DISTINCT name FROM cls WHERE stud_cat='$cat' and session='$session_year' ORDER BY uid") or die(mysqli_error());
			while($row5=mysqli_fetch_array($query5))
			{
			$c=$row5['name'];
			$this->Cell(30,6,$c." ".$d,1);
			$query50=mysqli_query($mysqli,"SELECT DISTINCT cat FROM category ORDER BY uid") or die(mysqli_error($mysqli));
			while($row50=mysqli_fetch_array($query50))
			{
				$ct=$row50['cat'];
				$cls=$c." ".$d;
				$query6=mysqli_query($mysqli,"SELECT seats FROM reserve WHERE pgender='$g' AND seat_cat='$cat' AND category='$ct' AND pclass='$cls' AND session='$session_year'") or die(mysqli_error($mysqli));
				$row6=mysqli_fetch_array($query6);
				if($ct=="PH")
				{
					$query7=mysqli_query($mysqli,"SELECT * FROM form_data WHERE pgender='$g' AND form_cat='$cat' AND ph='Yes' AND pclass='$cls' AND session='$session_year'") or die(mysqli_error($mysqli));
					$mycnt=mysqli_num_rows($query7);
				}
				else
				{
					$query7=mysqli_query($mysqli,"SELECT * FROM form_data WHERE pgender='$g' AND form_cat='$cat' AND category='$ct' AND pclass='$cls' AND session='$session_year'") or die(mysqli_error($mysqli));
					$mycnt=mysqli_num_rows($query7);
				}
				$this->Cell(13,6,$row6['seats'],1,0,'C');
				$this->Cell(14,6,$mycnt,1,0,'C');
				/*echo $row6['seats'];
				echo "(".$mycnt.")";*/
			}
		$this->Ln();
		}
	}
}
													
}


}


// Instanciation of inherited class
$pdf = new PDF();
$header = array('Name', 'Branch & Year', 'Category', 'Remarks');
// Data loading

$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('times','',10);


$pdf->BasicTable($header,$data);
	//$pdf->Output();
$p_ayear=$_POST['ayear'];
    $p_ses_cat=$_POST['ses_cat'];
    $p_gender=$_POST['gender'];
    $p_report_format=$_POST['report_format'];
	$pdf->Output($p_report_format." - Seat Distribution - ".$p_ayear." - ".$p_ses_cat." - ".$p_gender.".pdf", 'D');

	
	?>
